version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: semaphoreui
      POSTGRES_USER: semaphoreuiuser
      POSTGRES_PASSWORD: semaphoreuipassword
    volumes:
      - semaphoreui_postgres:/var/lib/postgresql/data
    networks:
      - semaphoreui_network

  semaphore:
    image: semaphoreui/semaphore:v2.10.32
    ports:
      - "3000:3000"
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_NAME: semaphoreui
      SEMAPHORE_DB_USER: semaphoreuiuser
      SEMAPHORE_DB_PASS: semaphoreuipassword
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@admin.com
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore
    networks:
      - semaphore_network

volumes:
  semaphore_data:
  semaphore_config:
  semaphore_tmp:
  semaphore_postgres:

networks:
  semaphore_network:
    driver: bridge