#################
# LEMP PLAYBOOK #
#################
---
- hosts: "all" # применяем команды ко всем хостам из inventory
  become: true # становимся привилегированным пользователем
  roles: 
  - semaphoreui

